import { Link, useNavigate } from 'react-router-dom'
import { useEffect, useRef } from 'react'
import { useStore } from '../store/StoreContext'
import { formatINR } from '../utils/cart'
import { classifyPriceBand } from '../utils/classifyPriceBand'
import { trackEvent } from '../analytics/trackEvent'
import { dispatchSoleSpectrumEvent } from '../analytics/dispatchSoleSpectrumEvent'
import { Summary } from '../components/Summary'

export function Cart() { const { cart, updateQuantity, removeFromCart } = useStore(); const navigate = useNavigate(); const initialCart = useRef(cart); const dispatchRemoval = (item, removedQuantity, removalType) => { const originalUnitPrice = Number(item.originalUnitPrice); const discountPercentage = Number(item.discountPercentage); const finalUnitPrice = Number(item.finalUnitPrice); const numericRemovedQuantity = Number(removedQuantity); if (!Number.isFinite(originalUnitPrice) || originalUnitPrice < 0 || !Number.isFinite(discountPercentage) || discountPercentage < 0 || !Number.isFinite(finalUnitPrice) || finalUnitPrice < 0 || !Number.isFinite(numericRemovedQuantity) || numericRemovedQuantity <= 0) return; dispatchSoleSpectrumEvent('soleSpectrumRemoveFromCart', { pageName: 'SoleSpectrum Cart', pageURL: window.location.href, sku: item.sku, productName: item.name, brand: item.brand, category: item.category, productTier: item.productTier, originalUnitPrice, discountPercentage, finalUnitPrice, purchasePriceBand: classifyPriceBand(finalUnitPrice), currency: item.currency, removedQuantity: numericRemovedQuantity, selectedSize: item.size, selectedColor: item.color, removedItemTotal: finalUnitPrice * numericRemovedQuantity, removalType }) }; useEffect(() => { trackEvent({ name: 'cartView', eventType: 'commerce.productViews', pageName: 'Cart', products: initialCart.current }) }, [initialCart]); const remove = (item) => { const currentItem = cart.find((cartItem) => cartItem.key === item.key); if (!currentItem) return; try { removeFromCart(currentItem.key) } catch { return } dispatchRemoval(currentItem, currentItem.quantity, 'full_removal'); trackEvent({ name: 'removeFromCart', eventType: 'commerce.productListRemovals', action: 'removeFromCart', pageName: 'Cart', products: [currentItem] }) }; const updateItemQuantity = (item, nextQuantity) => { const currentItem = cart.find((cartItem) => cartItem.key === item.key); if (!currentItem) return; const numericQuantity = Number(nextQuantity); const resultingQuantity = Number.isFinite(numericQuantity) ? Math.max(1, numericQuantity) : numericQuantity; const removedQuantity = currentItem.quantity - resultingQuantity; try { updateQuantity(currentItem.key, numericQuantity) } catch { return } if (Number.isFinite(removedQuantity) && removedQuantity > 0) dispatchRemoval(currentItem, removedQuantity, 'quantity_decrease') }
  return <main className="page"><div className="page-intro compact"><p className="eyebrow">Your selection / {cart.length} styles</p><h1>The <em>cart.</em></h1></div>{cart.length ? <div className="cart-layout"><div className="cart-list">{cart.map((item) => <article className="cart-item" key={item.key}><img src={item.image} alt="" /><div className="cart-item-main"><p className="product-brand">{item.brand} · {item.category}</p><h2>{item.name}</h2><p className="cart-meta">Size {item.size} · {item.color}</p><button className="remove-button" onClick={() => remove(item)}>Remove</button></div><div className="cart-item-controls"><label>Qty<input type="number" min="1" max="10" value={item.quantity} onChange={(event) => updateItemQuantity(item, Number(event.target.value))} /></label><strong>{formatINR(item.finalUnitPrice * item.quantity)}</strong></div></article>)}</div><Summary cart={cart} action={() => { trackEvent({ name: 'checkoutInitiation', eventType: 'commerce.checkouts', action: 'checkout', pageName: 'Cart', products: cart }); navigate('/checkout') }} /></div> : <div className="empty-state"><h2>Your cart is quiet.</h2><p>There are excellent shoes waiting in the collection.</p><Link className="button button-dark" to="/products">Browse shoes ↗</Link></div>}</main>
}
