import { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useStore } from '../store/StoreContext'
import { formatINR, getCartTotal } from '../utils/cart'
import { dispatchSoleSpectrumEvent } from '../analytics/dispatchSoleSpectrumEvent'
import { buildPurchaseEventData, hasTrackedPurchase, markPurchaseTracked } from '../utils/purchaseTracking'

export function Checkout() { const { cart, setCart } = useStore(); const navigate = useNavigate(); const [error, setError] = useState(''); const [form, setForm] = useState({ name: '', city: '', method: 'UPI' }); if (!cart.length) return <main className="page"><div className="empty-state"><h1>Nothing to check out.</h1><Link className="button button-dark" to="/products">Return to collection</Link></div></main>
  const submit = (event) => { event.preventDefault(); if (!form.name.trim() || !form.city.trim()) { setError('Please add a name and city to continue.'); return } const order = { purchaseId: `SS-${Date.now().toString(36).toUpperCase()}`, createdAt: new Date().toISOString(), items: cart, total: getCartTotal(cart), customerName: form.name.trim(), city: form.city.trim(), paymentMethod: form.method }; try { sessionStorage.setItem('sole-spectrum-order', JSON.stringify(order)) } catch { setError('Unable to create the order. Please try again.'); return } setCart([]); navigate('/confirmation'); const purchaseEventData = buildPurchaseEventData(order, window.location.href); if (purchaseEventData && !hasTrackedPurchase(order.purchaseId)) { try { const dispatched = dispatchSoleSpectrumEvent('soleSpectrumPurchase', purchaseEventData); if (dispatched) markPurchaseTracked(order.purchaseId) } catch (dispatchError) { void dispatchError } } }
  return <main className="page"><Link className="back-link" to="/cart">← Back to cart</Link><div className="checkout-layout"><form className="checkout-form" onSubmit={submit}><div className="page-intro compact"><p className="eyebrow">Almost there / mock checkout</p><h1>Make it <em>yours.</em></h1></div><fieldset><legend>Delivery details</legend><label>Name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="Test customer" /></label><label>City<input value={form.city} onChange={(event) => setForm({ ...form, city: event.target.value })} placeholder="Bengaluru" /></label></fieldset><fieldset><legend>Payment method</legend><div className="method-list">{['UPI', 'Card (mock)', 'Cash on delivery'].map((method) => <label key={method}><input type="radio" name="payment" checked={form.method === method} onChange={() => setForm({ ...form, method })} />{method}</label>)}</div><p className="muted">No payment details are stored or transmitted in this demo.</p></fieldset>{error && <p className="form-error" role="alert">{error}</p>}<button className="button button-dark" type="submit">Place mock order <span>↗</span></button></form><aside className="checkout-summary"><p className="eyebrow">Order summary</p>{cart.map((item) => <div className="mini-line" key={item.key}><span>{item.name} × {item.quantity}</span><strong>{formatINR(item.finalUnitPrice * item.quantity)}</strong></div>)}<div className="summary-total"><span>Total</span><strong>{formatINR(getCartTotal(cart))}</strong></div></aside></div></main>
}
