import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { ProductCard } from '../components/ProductCard'
import { categories, products } from '../data/products'
import { classifyPriceBand } from '../utils/classifyPriceBand'
import { trackEvent } from '../analytics/trackEvent'

export function Products() {
  const [params, setParams] = useSearchParams(); const [query, setQuery] = useState(params.get('q') || ''); const [category, setCategory] = useState('all'); const [band, setBand] = useState(params.get('band') || 'all'); const [sort, setSort] = useState('featured')
  const filtered = useMemo(() => products.filter((product) => (!query || `${product.name} ${product.brand}`.toLowerCase().includes(query.toLowerCase())) && (category === 'all' || product.category === category) && (band === 'all' || classifyPriceBand(product.finalUnitPrice) === band)).sort((a, b) => sort === 'low' ? a.finalUnitPrice - b.finalUnitPrice : sort === 'high' ? b.finalUnitPrice - a.finalUnitPrice : Number(b.featured) - Number(a.featured)), [query, category, band, sort])
  useEffect(() => { if (query) trackEvent({ name: 'search', eventType: 'web.webinteraction.linkClicks', pageName: 'Collection', details: { query } }); }, [query])
  const updateFilter = (setter, value, field) => { setter(value); trackEvent({ name: 'filterInteraction', eventType: 'web.webinteraction.linkClicks', pageName: 'Collection', details: { filter: field, value } }) }
  return <main className="page"><div className="page-intro"><p className="eyebrow">Collection / {filtered.length} results</p><h1>All the good<br /><em>possibilities.</em></h1></div><div className="filter-bar"><label className="search-field"><span>Search</span><input value={query} onChange={(event) => { setQuery(event.target.value); setParams(event.target.value ? { q: event.target.value } : {}) }} placeholder="Name or brand" /></label><label>Category<select value={category} onChange={(event) => updateFilter(setCategory, event.target.value, 'category')}>{categories.map((item) => <option key={item} value={item}>{item.replace('_', ' ')}</option>)}</select></label><label>Price band<select value={band} onChange={(event) => updateFilter(setBand, event.target.value, 'priceBand')}><option value="all">All bands</option><option value="budget">Budget</option><option value="mid_range">Mid-range</option><option value="premium">Premium</option></select></label><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="featured">Featured</option><option value="low">Price: low first</option><option value="high">Price: high first</option></select></label></div>{filtered.length ? <div className="product-grid collection-grid">{filtered.map((product) => <ProductCard key={product.id} product={product} onClick={() => trackEvent({ name: 'productClick', eventType: 'web.webinteraction.linkClicks', action: 'productView', pageName: 'Collection', products: [product] })} />)}</div> : <div className="empty-state"><h2>No shoes found.</h2><p>Try another name, category, or price band.</p></div>}</main>
}
