import { useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ProductCard } from '../components/ProductCard'
import { useStore } from '../store/StoreContext'
import { formatINR } from '../utils/cart'
import { classifyPriceBand } from '../utils/classifyPriceBand'
import { trackEvent } from '../analytics/trackEvent'
import { dispatchSoleSpectrumEvent } from '../analytics/dispatchSoleSpectrumEvent'

export function ProductDetail() { const { id } = useParams(); const { products, addToCart } = useStore(); const navigate = useNavigate(); const product = products.find((item) => item.id === id); const viewedProductId = useRef(null); const [size, setSize] = useState(product?.availableSizes[0] || ''); const [color, setColor] = useState(product?.availableColors[0] || ''); const [quantity, setQuantity] = useState(1)
  useEffect(() => { if (product && viewedProductId.current !== product.id) { viewedProductId.current = product.id; trackEvent({ name: 'productDetailView', eventType: 'commerce.productViews', action: 'productView', pageName: product.name, products: [product] }); dispatchSoleSpectrumEvent('soleSpectrumProductView', { pageName: 'SoleSpectrum Product Detail', pageURL: window.location.href, sku: product.sku, productName: product.name, brand: product.brand, category: product.category, productTier: product.productTier, originalUnitPrice: product.originalUnitPrice, discountPercentage: product.discountPercentage, finalUnitPrice: product.finalUnitPrice, purchasePriceBand: classifyPriceBand(product.finalUnitPrice), currency: product.currency }) } }, [product])
  if (!product) return <main className="page"><div className="empty-state"><h1>That pair walked off.</h1><Link className="button button-dark" to="/products">Back to collection</Link></div></main>
  const add = () => { const numericQuantity = Number(quantity); const originalUnitPrice = Number(product.originalUnitPrice); const discountPercentage = Number(product.discountPercentage); const finalUnitPrice = Number(product.finalUnitPrice); if (!product.availableSizes.includes(size) || !product.availableColors.includes(color) || !Number.isFinite(numericQuantity) || numericQuantity <= 0 || !Number.isFinite(originalUnitPrice) || !Number.isFinite(discountPercentage) || !Number.isFinite(finalUnitPrice)) return; try { addToCart(product, size, color, numericQuantity) } catch { return } dispatchSoleSpectrumEvent('soleSpectrumAddToCart', { pageName: 'SoleSpectrum Product Detail', pageURL: window.location.href, sku: product.sku, productName: product.name, brand: product.brand, category: product.category, productTier: product.productTier, originalUnitPrice, discountPercentage, finalUnitPrice, purchasePriceBand: classifyPriceBand(finalUnitPrice), currency: product.currency, quantity: numericQuantity, selectedSize: size, selectedColor: color, itemTotal: finalUnitPrice * numericQuantity }); trackEvent({ name: 'addToCart', eventType: 'commerce.productListAdds', action: 'addToCart', pageName: product.name, products: [{ ...product, size, color, quantity: numericQuantity }] }); navigate('/cart') }
  return <main className="page detail-page"><Link className="back-link" to="/products">← Back to collection</Link><div className="detail-layout"><div className="detail-image"><img src={product.image} alt={product.name} /></div><div className="detail-copy"><p className="eyebrow">{product.brand} / {product.sku}</p><h1>{product.name}</h1><p className="detail-description">{product.description}</p><div className="detail-price"><strong>{formatINR(product.finalUnitPrice)}</strong>{product.discountPercentage > 0 && <><del>{formatINR(product.originalUnitPrice)}</del><span>{product.discountPercentage}% off</span></>}</div><dl className="spec-list"><div><dt>Category</dt><dd>{product.category}</dd></div><div><dt>Product tier</dt><dd>{product.productTier.replace('_', '-')}</dd></div><div><dt>Purchase band</dt><dd><span className={`band band-${classifyPriceBand(product.finalUnitPrice)}`}>{classifyPriceBand(product.finalUnitPrice).replace('_', ' ')}</span></dd></div></dl><div className="option-row"><fieldset><legend>Size</legend><div className="choice-list">{product.availableSizes.map((item) => <button className={size === item ? 'selected' : ''} key={item} onClick={() => setSize(item)}>{item}</button>)}</div></fieldset><fieldset><legend>Colour</legend><div className="choice-list">{product.availableColors.map((item) => <button className={color === item ? 'selected' : ''} key={item} onClick={() => setColor(item)}>{item}</button>)}</div></fieldset></div><div className="purchase-row"><label>Quantity<input type="number" min="1" max="10" value={quantity} onChange={(event) => setQuantity(Math.max(1, Number(event.target.value) || 1))} /></label><button className="button button-dark" onClick={add}>Add to cart <span>↗</span></button></div></div></div></main>
}
